### ISSUE TITLE
Crash on login with new char

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#7]
Hello, i have just compiled Edelstein on Win7 64x setup the path for nx/scripts and then tried to login via v95localhost i found on ragezone. Compilation went ok, however the client crashes on login. Theres no exception being thrown in VS. Heres the screen: 
![crash](https://user-images.githubusercontent.com/2548763/58370995-6e19d580-7f0d-11e9-9da4-5f4fa3dba539.png)

btw why is the console formatted so messy o.o?

**Comment by Kaioru** [comment]
Hey hey, thanks for checking out Edelstein!

1. It might be a client issue, I'll send you the client I'm using atm on Discord.
2. If I'm not wrong it might be because ANSI Color Codes might not be supported in your environment. The Serilog theme it is using by default is: 'Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code'

An alternative is changing appsettings.json 'Serilog' option to:
```json
"Serilog": {
    "MinimumLevel": "Information",
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "theme": "Serilog.Sinks.SystemConsole.Themes.ConsoleTheme::None, Serilog.Sinks.Console"
        }
      }
    ]
  }
```
Which will remove any theming for the logs.

Feel free to contact me on Discord or on here for further questions!

**Comment by Bia10** [comment]
Hi there,

the client you sent me solved the crashing.. however there are certain rules for autoregister if you fail them it throws useless maple-client error login not found. We should write these down somewhere.

Secondly for the console i dunno why but it seems i am unable to use AnsiConsoleThemes but i can use SystemConsoleThemes. i have changed the serilog settings to

![serrilog](https://user-images.githubusercontent.com/2548763/58537529-597e5b80-81f3-11e9-97dc-9bff4f1b0bf3.png)

and things looks fine now

![cnsole](https://user-images.githubusercontent.com/2548763/58536929-17084f00-81f2-11e9-8ca2-9fc1121fa92f.png)
